"""Kaputt DINOv3-L — Reference-Enhanced Noise-Robust Training (from scratch)
============================================================================
Trains from the pretrained DINOv3-L backbone (NOT from a Phase-1 checkpoint)
on query data + pseudo-labeled reference images.

Training from pretrained backbone avoids confirmation bias: the teacher
(Phase-1 model) generates pseudo-labels, but the student starts fresh and
can learn patterns the teacher missed.

The reference data is nominally "non-defective" but empirically only ~20%
are truly normal.  We handle this through:
  1. Teacher pseudo-labeling  (generate_pseudo_labels.py)
  2. Confidence-based filtering (conf_thresh_normal / conf_thresh_defect)
  3. Noise-robust loss (NoisyRobustFocalLoss: Focal + symmetric RCE)

Workflow:
    Step 1 — Train a teacher model on query data only:
        python train_vit_mm.py configs/large_728_three_freeze.py

    Step 2 — Generate pseudo-labels with the teacher:
        python generate_pseudo_labels.py \
            --config configs/large_728_three_freeze.py \
            --checkpoint <TEACHER_BEST_CKPT> \
            --data-root /data/public/dataset/kaputt \
            --parquet-root /data/public/dataset/kaputt \
            --output pseudo_labels_ref.csv \
            --tta-scales 512 728 960

    Step 3 — Train student from scratch with reference data:
        python train_vit_mm.py configs/large_728_ref.py

    Step 4 — (Optional) Iterative refinement:
        # Use the student model as the new teacher to re-pseudo-label
        python generate_pseudo_labels.py \
            --config configs/large_728_ref.py \
            --checkpoint work_dirs/kaputt_dinov3_l_ref/best.pth \
            ...
        python train_vit_mm.py configs/large_728_ref.py
"""

# ======================== Backbone Selection ========================
backbone_name = 'dinov3_h'

_REGISTRY = dict(
    dinov2_b=dict(timm='vit_base_patch14_dinov2.lvd142m',           ch=768,  ps=14),
    dinov2_l=dict(timm='vit_large_patch14_dinov2.lvd142m',          ch=1024, ps=14),
    dinov2_l_reg=dict(timm='vit_large_patch14_reg4_dinov2.lvd142m', ch=1024, ps=14),
    dinov2_g=dict(timm='vit_giant_patch14_dinov2.lvd142m',          ch=1536, ps=14),
    dinov3_b=dict(timm='vit_base_patch16_dinov3.lvd1689m',          ch=768,  ps=16),
    dinov3_l=dict(timm='vit_large_patch16_dinov3.lvd1689m',         ch=1024, ps=16),
    dinov3_h=dict(timm='vit_huge_plus_patch16_dinov3.lvd1689m',     ch=1280, ps=16),
    dinov3_7b=dict(timm='vit_7b_patch16_dinov3.lvd1689m',           ch=4096, ps=16),
)
_bb = _REGISTRY[backbone_name]

# ======================== Image Size ================================
target_img_size = 728
patch_size = _bb['ps']
img_size = (target_img_size // patch_size) * patch_size

# ======================== Data Paths ================================
data_root = '/data/public/dataset/kaputt'
parquet_root = '/data/public/dataset/kaputt'

# Path to pseudo-labels CSV generated by generate_pseudo_labels.py
pseudo_label_file = './pseudo_labels_ref.csv'

# ======================== Runtime ===================================
default_scope = 'mmpretrain'
work_dir = f'./work_dirs/kaputt_{backbone_name}_ref'

# ======================== Checkpoint ================================
# Train from pretrained DINOv3-L backbone (no Phase-1 checkpoint).
# This avoids confirmation bias — the student model starts fresh and
# can learn patterns the teacher missed.
load_from = None
resume = False

# ======================== Model =====================================
model = dict(
    type='ImageClassifier',
    data_preprocessor=dict(
        num_classes=2,
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True,
    ),
    backbone=dict(
        type='TIMMBackbone',
        model_name=_bb['timm'],
        pretrained=True,
        img_size=img_size,
    ),
    neck=dict(type='CLSTokenNeck'),
    head=dict(
        type='LinearClsHead',
        num_classes=2,
        in_channels=_bb['ch'],
        # NoisyRobustFocalLoss = Focal + symmetric RCE for noise robustness
        # beta controls the strength of noise-robust regularisation:
        #   beta=0   : equivalent to SoftFocalLoss
        #   beta=0.5 : moderate noise robustness (recommended)
        #   beta=1.0 : strong noise robustness
        loss=dict(
            type='NoisyRobustFocalLoss',
            gamma=2.0,
            alpha=0.75,
            beta=0.5,
            eps=1e-4,
            ohem_ratio=0.7,
            loss_weight=1.0,
        ),
    ),
)

model_wrapper_cfg = dict(find_unused_parameters=True)

# ======================== Data Pipelines ============================
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='RandomResizedCrop', scale=img_size,
         crop_ratio_range=(0.95, 1.0),
         interpolation='bicubic', backend='pillow'),
    dict(type='RandomFlip', prob=0.5, direction='horizontal'),
    dict(type='RandomFlip', prob=0.5, direction='vertical'),
    dict(type='RandomRotation90'),
    dict(type='ColorJitter', brightness=0.2, contrast=0.2,
         saturation=0.15, hue=0.04),
    dict(type='PackInputs'),
]

val_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='Resize', scale=(img_size, img_size),
         interpolation='bicubic', backend='pillow'),
    dict(type='PackInputs'),
]

# ======================== DataLoaders ===============================
batch_size_per_gpu = 56
num_workers = 8

# Training set: query (train+val+test) + pseudo-labeled reference data
# Key parameters for noise handling:
#   conf_thresh_normal : reference images with defect_prob BELOW this
#                        are treated as normal (label=0)
#   conf_thresh_defect : reference images with defect_prob ABOVE this
#                        are treated as defective (label=1)
#   max_ref_ratio      : cap reference count at this ratio of query count
#   ref_repeat_defect  : repeat pseudo-defective reference samples to
#                        help balance (reference data is skewed towards
#                        pseudo-defective since ~80% have defects)
train_dataloader = dict(
    batch_size=batch_size_per_gpu,
    num_workers=num_workers,
    persistent_workers=True,
    pin_memory=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    dataset=dict(
        type='ReferenceEnhancedKaputtDataset',
        ann_files=[
            f'{parquet_root}/query-train.parquet',
            f'{parquet_root}/query-validation.parquet',
            f'{parquet_root}/query-test.parquet',
        ],
        data_prefixes=[
            f'{data_root}/data/train/query-data/crop',
            f'{data_root}/data/validation/query-data/crop',
            f'{data_root}/data/test/query-data/crop',
        ],
        pseudo_label_file=pseudo_label_file,
        conf_thresh_normal=0.46,
        conf_thresh_defect=0.66,
        max_ref_ratio=0.5,
        ref_repeat_defect=1,
        pipeline=train_pipeline,
    ),
)

val_dataloader = dict(
    batch_size=batch_size_per_gpu * 2,
    num_workers=num_workers,
    persistent_workers=True,
    pin_memory=True,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type='KaputtDataset',
        ann_file=f'{parquet_root}/query-test.parquet',
        data_prefix=dict(
            img_path=f'{data_root}/data/test/query-data/crop'),
        pipeline=val_pipeline,
    ),
)

test_dataloader = val_dataloader

# ======================== Evaluator =================================
val_evaluator = [
    dict(type='Accuracy', topk=(1,)),
    dict(type='BinaryAPMetric'),
    dict(type='MaterialAPMetric',
         parquet_path=f'{parquet_root}/query-test.parquet',
         material='plastic_tight_wrap'),
]
test_evaluator = val_evaluator

# ======================== Optimizer =================================
# Same LR as Phase-1 since we're training from pretrained backbone
optim_wrapper = dict(
    type='AmpOptimWrapper',
    accumulative_counts=1,
    optimizer=dict(
        type='AdamW',
        lr=1e-5,
        weight_decay=0.05,
        betas=(0.9, 0.999),
    ),
    paramwise_cfg=dict(
        custom_keys=dict(
            head=dict(lr_mult=20.0, decay_mult=0.1),  # head LR = 2e-4
        ),
    ),
    clip_grad=dict(max_norm=1.0),
)

# ======================== LR Schedule ===============================
epochs = 15
warmup_epochs = 3

param_scheduler = [
    dict(type='LinearLR', start_factor=1e-3,
         by_epoch=True, begin=0, end=warmup_epochs),
    dict(type='CosineAnnealingLR', eta_min=1e-7,
         by_epoch=True, begin=warmup_epochs, end=epochs),
]

train_cfg = dict(by_epoch=True, max_epochs=epochs, val_interval=1)
val_cfg = dict()
test_cfg = dict()

# ======================== Hooks =====================================
default_hooks = dict(
    timer=dict(type='IterTimerHook'),
    logger=dict(type='LoggerHook', interval=50),
    param_scheduler=dict(type='ParamSchedulerHook'),
    checkpoint=dict(
        type='CheckpointHook',
        interval=1,
        max_keep_ckpts=12,
        save_best=['material_ap/AP', 'binary_ap/AP'],
        rule='greater',
    ),
    sampler_seed=dict(type='DistSamplerSeedHook'),
)

# From-scratch training: conservative gradual unfreezing
# (same schedule as Phase-1 — head first, then progressively open backbone)
custom_hooks = [
    dict(
        type='GradualUnfreezeHook',
        grad_checkpointing=True,
        unfreeze_schedule={
              1: 0,    # epoch 1-2 : head only
              4: 6,    # epoch 3-4 : last 6 blocks
              7: 12,   # epoch 5-7 : last 12 blocks
              10: 20,  # epoch 8+  : last 20 blocks
        },
    ),
    dict(type='SWAHook', swa_start_epoch=15, swa_freq=1),
    dict(type='EarlyStoppingHook', monitor='material_ap/AP',
         patience=15, rule='greater'),
]

# ======================== Visualizer ================================
visualizer = dict(
    type='UniversalVisualizer',
    vis_backends=[
        dict(type='LocalVisBackend'),
        dict(type='TensorboardVisBackend'),
    ],
)

# ======================== Environment ===============================
env_cfg = dict(
    cudnn_benchmark=True,
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0),
    dist_cfg=dict(backend='nccl'),
)

randomness = dict(seed=3407, deterministic=False)

log_level = 'INFO'
